package com.neuedu.dao;

import com.neuedu.pojo.Cat;
import java.util.List;

public interface CatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cat
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cat
     *
     * @mbg.generated
     */
    int insert(Cat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cat
     *
     * @mbg.generated
     */
    Cat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cat
     *
     * @mbg.generated
     */
    List<Cat> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cat
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cat record);
}