package com.neuedu.dao;

import com.neuedu.pojo.Goods;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Set;

public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    Goods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    List<Goods> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Goods record);
    /**
     * 更新商品
     * **/
    int updateGoodsKeySelective(Goods goods);
    /**
     * 按照productId或者productName查询
     * **/
    List<Goods> findGoodsByGoodsIdAndGoodsName(@Param("goodsId") Integer goodsId,
                                                       @Param("goodsName") String goodsName);

    /**
     * 前台-搜索商品
     * **/
    List<Goods> searchGoods(@Param("integerSet") Set<Integer> integerSet,
                                @Param("keyword") String keyword);


}